### ISSUE TITLE
watch our progress

### ISSUE THREAD

**Issue by kidatsy** [smithln/ctl#11]
Hey Lauren,

Great to see the progress! This isn't really an issue per se, just wanted to let you know that I've started on the process of integrating your good work into the site, which you can check at https://github.com/CrisisTextLine/CTL-Online/tree/pattern_library. We're importing this repo as a submodule and recompiling your SASS with our own tweaks to fit into Drupal-land.

Thanks!
TC

**Comment by smithln** [comment]
Thanks @kidat !
