### ISSUE TITLE
Menu Bar

### ISSUE THREAD

**Issue by smithln** [smithln/ctl#8]
Styling for navigation - 

@cjcodes, can you give some thought here on what would work with drupal? 

![screenshot 2015-04-03 08 41 59](https://cloud.githubusercontent.com/assets/5695193/6982907/4ea6f090-d9dd-11e4-861c-a2d1876a032b.png)

**Comment by smithln** [comment]
@cjcodes ping

**Comment by cjcodes** [comment]
![screen shot 2015-04-14 at 3 07 55 pm](https://cloud.githubusercontent.com/assets/805867/7145144/0af05240-e2b8-11e4-96c1-1c68e61ac1a4.png)

And some sample HTML:

``` html
<ul class="tabs primary"><li class="active"><a href="/admin/part-one" class="active">Rejected<span class="element-invisible">(active tab)</span></a></li>
<li><a href="/admin/part-one/waiting">Waiting</a></li>
<li><a href="/admin/part-one/accepted">Accepted to Part Two (not started)</a></li>
<li><a href="/admin/part-one/applying">Started Part Two</a></li>
</ul>
```

**Comment by smithln** [comment]
@cjcodes After playing around with this, I think it makes more sense to just do the following: 

Make sure fonts are set to `$font-family-sans-serif` (Roboto)
Make sure `<li>` items are the following: 

`li {
letter-spacing: .1rem;
text-transform: uppercase;
}
`

and that active tabs use `$brand-primary` (red) in the `border-top` styling.
