### ISSUE TITLE
Tables

### ISSUE THREAD

**Issue by smithln** [smithln/ctl#9]
![screenshot 2015-04-03 08 41 59](https://cloud.githubusercontent.com/assets/5695193/6982923/6b793bc4-d9dd-11e4-82ae-6b26a98bc8fa.png)

**Comment by cjcodes** [comment]
- Striped table
- Hover class that works with the stripe
- <th> classes for headers

**Comment by cjcodes** [comment]
Here's a common Drupal table:

![screen shot 2015-04-14 at 3 01 17 pm](https://cloud.githubusercontent.com/assets/805867/7145264/fba5f7f8-e2b8-11e4-984c-4835658dd6c5.png)

And some sample markup:

``` html
<table class="views-table cols-6">
  <thead>
    <tr>
      <th>
        <div class="form-item form-type-checkbox">
          <input class="form-checkbox" type="checkbox" value="1" style="display: inline-block;">
        </div>
      </th>
      <th>
        <a href="#" title="sort by Name" class="active">Name</a>
      </th>
    </tr>
  </thead>
  <tbody>
    <tr class="odd"> <!-- or even -->
      <td>
        <div class="form-item form-type-checkbox form-item-views-bulk-operations-0">
          <input class="vbo-select form-checkbox" type="checkbox" id="" name="" value="40">
        </div>
      </td>
      <td>
        <a href="#" title="View user profile." class="username">Some Dude</a>
      </td>
    </tr>
  </tbody>
</table>
```

**Comment by smithln** [comment]
@cjcodes - 

Again, similar to the menu bars - after playing around with this I think it makes sense to just do the following: 

Make sure type is `$font-family-sans-serif` (Roboto)

We can keep iterating on this in the future, but I don't feel that styling this should be a launch blocker. I think the other elements we have in place are going to separate this from default styling enough that we can tackle things like this at a later date or even v2.
